# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPlXEu_OlNN3Dj0NFGOh91i_UZF4xbbv
"""

import pandas as pd

# Load the datasets into variables
df_a = pd.read_csv('frauddetection.csv')
df_b = pd.read_csv('creditcard.csv')

# Load Credit Card dataset
creditcard_path = "creditcard.csv"
credit_df = pd.read_csv(creditcard_path)

# Load Fraud Detection (PaySim) dataset
fraud_path = "frauddetection.csv"
fraud_df = pd.read_csv(fraud_path)

# Quick checks
print("Credit Card Dataset:")
print(credit_df.shape)
print(credit_df.head())

print("\nFraud Detection Dataset:")
print(fraud_df.shape)
print(fraud_df.head())

# Dataset summaries
print("\nCredit Card Info:")
print(credit_df.info())
print(credit_df.describe())

print("\nFraud Detection Info:")
print(fraud_df.info())
print(fraud_df.describe())

#Analyze class imbalance
def analyze_imbalance(df, target_col, dataset_name):
    """Show class distribution with pretty tables"""
    total = len(df)
    fraud = df[target_col].sum()
    legit = total - fraud
    fraud_pct = (fraud / total) * 100

    print(f"\n{'='*60}")
    print(f"{dataset_name} - CLASS DISTRIBUTION")
    print(f"{'='*60}")

    # Create summary table
    summary = pd.DataFrame({
        'Class': ['Legitimate', 'Fraudulent', 'TOTAL'],
        'Count': [f"{legit:,}", f"{fraud:,}", f"{total:,}"],
        'Percentage': [f"{100-fraud_pct:.3f}%", f"{fraud_pct:.3f}%", "100.000%"],
        'Ratio': [f"{legit/fraud:.1f}:1", "1:1", "-"]
    })
    display(summary)

    print(f"\n⚠️  CRITICAL INSIGHT:")
    print(f"    Only {fraud_pct:.3f}% are frauds!")
    print(f"    If we predict ALL as legitimate → {100-fraud_pct:.3f}% accuracy")
    print(f"    BUT we catch ZERO frauds! Accuracy is MISLEADING!")

    return fraud, legit, fraud_pct

# Analyze both datasets
cc_stats = analyze_imbalance(credit_df, 'Class', 'CREDIT CARD')
ps_stats = analyze_imbalance(fraud_df, 'isFraud', 'PAYSIM')